#!/bin/sh

# Enable keyboard backlight

PATH=/sbin:/usr/sbin:/bin:/usr/bin

if [ ! -x /usr/share/unattended-upgrades/unattended-upgrade-shutdown ]; then
	exit 0
fi

case "${1}" in
        resume|thaw)
                echo 3 > /sys/class/leds/asus::kbd_backlight/brightness
                ;;
esac

